  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Afghanistan', 'AF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Åland Islands', 'AX');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Albania', 'AL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Algeria', 'DZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'American Samoa', 'AS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'AndorrA', 'AD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Angola', 'AO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Anguilla', 'AI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Antarctica', 'AQ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Antigua and Barbuda', 'AG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Argentina', 'AR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Armenia', 'AM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Aruba', 'AW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Australia', 'AU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Austria', 'AT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Azerbaijan', 'AZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bahamas', 'BS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bahrain', 'BH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bangladesh', 'BD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Barbados', 'BB');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Belarus', 'BY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Belgium', 'BE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Belize', 'BZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Benin', 'BJ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bermuda', 'BM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bhutan', 'BT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bolivia', 'BO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bosnia and Herzegovina', 'BA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Botswana', 'BW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bouvet Island', 'BV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Brazil', 'BR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'British Indian Ocean Territory', 'IO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Brunei Darussalam', 'BN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Bulgaria', 'BG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Burkina Faso', 'BF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Burundi', 'BI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cambodia', 'KH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cameroon', 'CM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Canada', 'CA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cape Verde', 'CV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cayman Islands', 'KY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Central African Republic', 'CF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Chad', 'TD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Chile', 'CL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'China', 'CN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Christmas Island', 'CX');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cocos (Keeling) Islands', 'CC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Colombia', 'CO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Comoros', 'KM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Congo', 'CG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Congo, The Democratic Republic of the', 'CD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cook Islands', 'CK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Costa Rica', 'CR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cote Ivoire', 'CI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Croatia', 'HR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cuba', 'CU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Cyprus', 'CY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Czech Republic', 'CZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Denmark', 'DK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Djibouti', 'DJ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Dominica', 'DM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Dominican Republic', 'DO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Ecuador', 'EC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Egypt', 'EG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'El Salvador', 'SV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Equatorial Guinea', 'GQ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Eritrea', 'ER');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Estonia', 'EE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Ethiopia', 'ET');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Falkland Islands (Malvinas)', 'FK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Faroe Islands', 'FO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Fiji', 'FJ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Finland', 'FI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'France', 'FR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'French Guiana', 'GF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'French Polynesia', 'PF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'French Southern Territories', 'TF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Gabon', 'GA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Gambia', 'GM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Georgia', 'GE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Germany', 'DE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Ghana', 'GH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Gibraltar', 'GI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Greece', 'GR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Greenland', 'GL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Grenada', 'GD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guadeloupe', 'GP');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guam', 'GU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guatemala', 'GT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guernsey', 'GG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guinea', 'GN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guinea-Bissau', 'GW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Guyana', 'GY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Haiti', 'HT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Heard Island and Mcdonald Islands', 'HM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Holy See (Vatican City State)', 'VA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Honduras', 'HN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Hong Kong', 'HK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Hungary', 'HU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Iceland', 'IS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'India', 'IN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Indonesia', 'ID');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Iran, Islamic Republic Of', 'IR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Iraq', 'IQ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Ireland', 'IE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Isle of Man', 'IM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Israel', 'IL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Italy', 'IT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Jamaica', 'JM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Japan', 'JP');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Jersey', 'JE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Jordan', 'JO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Kazakhstan', 'KZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Kenya', 'KE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Kiribati', 'KI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Korea, Democratic People Republic of', 'KP');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Korea, Republic of', 'KR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Kuwait', 'KW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Kyrgyzstan', 'KG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Lao People Democratic Republic', 'LA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Latvia', 'LV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Lebanon', 'LB');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Lesotho', 'LS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Liberia', 'LR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Libyan Arab Jamahiriya', 'LY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Liechtenstein', 'LI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Lithuania', 'LT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Luxembourg', 'LU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Macao', 'MO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Macedonia, The Former Yugoslav Republic of', 'MK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Madagascar', 'MG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Malawi', 'MW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Malaysia', 'MY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Maldives', 'MV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mali', 'ML');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Malta', 'MT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Marshall Islands', 'MH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Martinique', 'MQ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mauritania', 'MR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mauritius', 'MU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mayotte', 'YT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mexico', 'MX');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Micronesia, Federated States of', 'FM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Moldova, Republic of', 'MD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Monaco', 'MC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mongolia', 'MN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Montserrat', 'MS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Morocco', 'MA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Mozambique', 'MZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Myanmar', 'MM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Namibia', 'NA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Nauru', 'NR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Nepal', 'NP');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Netherlands', 'NL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Netherlands Antilles', 'AN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'New Caledonia', 'NC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'New Zealand', 'NZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Nicaragua', 'NI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Niger', 'NE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Nigeria', 'NG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Niue', 'NU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Norfolk Island', 'NF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Northern Mariana Islands', 'MP');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Norway', 'NO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Oman', 'OM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Pakistan', 'PK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Palau', 'PW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Palestinian Territory, Occupied', 'PS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Panama', 'PA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Papua New Guinea', 'PG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Paraguay', 'PY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Peru', 'PE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Philippines', 'PH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Pitcairn', 'PN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Poland', 'PL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Portugal', 'PT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Puerto Rico', 'PR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Qatar', 'QA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Reunion', 'RE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Romania', 'RO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Russian Federation', 'RU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'RWANDA', 'RW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saint Helena', 'SH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saint Kitts and Nevis', 'KN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saint Lucia', 'LC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saint Pierre and Miquelon', 'PM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saint Vincent and the Grenadines', 'VC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Samoa', 'WS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'San Marino', 'SM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Sao Tome and Principe', 'ST');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Saudi Arabia', 'SA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Senegal', 'SN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Serbia and Montenegro', 'CS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Seychelles', 'SC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Sierra Leone', 'SL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Singapore', 'SG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Slovakia', 'SK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Slovenia', 'SI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Solomon Islands', 'SB');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Somalia', 'SO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'South Africa', 'ZA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'South Georgia and the South Sandwich Islands', 'GS');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Spain', 'ES');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Sri Lanka', 'LK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Sudan', 'SD');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Suriname', 'SR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Svalbard and Jan Mayen', 'SJ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Swaziland', 'SZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Sweden', 'SE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Switzerland', 'CH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Syrian Arab Republic', 'SY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Taiwan, Province of China', 'TW');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tajikistan', 'TJ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tanzania, United Republic of', 'TZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Thailand', 'TH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Timor-Leste', 'TL');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Togo', 'TG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tokelau', 'TK');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tonga', 'TO');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Trinidad and Tobago', 'TT');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tunisia', 'TN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Turkey', 'TR');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Turkmenistan', 'TM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Turks and Caicos Islands', 'TC');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Tuvalu', 'TV');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Uganda', 'UG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Ukraine', 'UA');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'United Arab Emirates', 'AE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'United Kingdom', 'GB');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'United States', 'US');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'United States Minor Outlying Islands', 'UM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Uruguay', 'UY');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Uzbekistan', 'UZ');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Vanuatu', 'VU');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Venezuela', 'VE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Viet Nam', 'VN');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Virgin Islands, British', 'VG');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Virgin Islands, U.S.', 'VI');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Wallis and Futuna', 'WF');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Western Sahara', 'EH');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Yemen', 'YE');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Zambia', 'ZM');
  INSERT INTO public.country (cou_name, cou_code) VALUES ( 'Zimbabwe', 'ZW');